### ISSUE TITLE
problematic apartment matching

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/parcel#37]
Seems like some apartment complexes are listed under one or two (sometimes none) street numbers in CAGIS, when in reality their associated mailing addresses range in street number (i.e., the auditor lists the whole complex under `2702 Whatever St` and real addresses are `2710`, `2711`, etc..)

I have real examples from birth record addresses... this could be causing potentially thousands of addresses to be unmatched.

**Comment by cole-brokamp** [comment]
Yes, I've seen this too with other apartment complexes; the mailing address does not always have the same street number (or sometimes street name) and the associated parcel address.  

Maybe like our known non-institutional address list, we can make a list of known cases where the mailing address and parcel address are different.  Then we could still assign the correct parcel identifier, but not have to manually update the pulled data from the auditor's database.

For example, (a bad example since it is for Ronald McDonald House and it would be a moot point anyway..., but) 340 Erkenbrecher and 351 Erkenbrecher are two addresses with one parcel identifier: https://wedge3.hcauditor.org/view/re/1130004017500/2022/summary  The parcel identifier is listed as `341-350 ERKENBRECHER AVE`

Another example is Stetson Square apartments: https://wedge3.hcauditor.org/view/re/1040004024000/2022/summary

I think it would be OK for us to generate a list of known mailing addresses that do not match with the parcel address here and implement that into our matching process.

**Comment by erikarasnick** [comment]
create additional step after initial parcel match -- if unmatched look for these problematic apartments
